[tool.poetry]
name = "home-work20-2"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "home_work20"}]

[tool.poetry.dependencies]
python = "^3.11"
template = "^0.7.6"
django = "^4.2.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
